#!/usr/bin/env python3

import sys

from rqt_gui.main import Main

plugin = 'rqt_network.ROSNetwork'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
